README.md, package-lock.json, package.json, src/App.tsx, src/components/FNB/index.tsx, src/components/LoanProductCard.tsx, src/components/Nav/index.tsx, src/libs/utils.ts, src/pages/main/TotalLoans.tsx, src/pages/main/index.tsx, src/pages/user/Edit.tsx, tailwind.config.cjs
- `"@types/react-icons": "^3.0.0"` 설치
[페이지명]
- Home
- Main
- user/edit
- Nav 컴포넌트 
- LoanProductCard.tsx 컴포넌트
[작업제목]
- 작업내용
- 작업내용
#2 
> Home
> Main
> user/edit
=> feat: home, main, user/edit 페이지 스타일링

src/App.tsx, src/components/FinancialProdCard.tsx, src/pages/products/financial/index.tsx, tailwind.config.cjs
- 공통 App style 수정
- tailwind.config 변수 추가
- Create Financial Page
- Create FinancialProdCard Component
- Modify tailwind.config.cjs (커스텀 컬러 추가)
- App style 추가 (max-width, height:100vh)
- Modify tailwind.config.cjs (커스텀 컬러 추가)
- App style 추가 (max-width, height:100vh)
=> Feat: Create Financial Page

src/App.tsx, src/components/OrderList/OrderListElement.tsx, src/components/ui/Navigation/index.tsx, src/pages/main/index.tsx, src/pages/user/Edit.tsx, src/pages/user/MyCart.tsx, src/pages/user/WishList.tsx, src/pages/user/index.tsx
- 몇몇 파일에서 절대경로로 작은 수정
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> edit: absolute path

src/App.tsx, src/DevLinks.tsx, src/env.d.ts, src/index.tsx, src/libs/axiosClient.ts, src/libs/hooks/useGetUser.tsx, src/libs/hooks/useLogin.tsx, src/libs/hooks/useToken.tsx, src/pages/home/index.tsx, src/pages/user/Edit.tsx
useLogin 및, useHook 과 사이드 에서 로그인할수 있는 메뉴를 추가했습니다.
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> feat: useLogin, useToken

package-lock.json, package.json, src/libs/axiosClient.ts, src/libs/hooks/useGetProducts.tsx, src/libs/hooks/useGetRecommendsProducts.tsx, src/libs/hooks/useGetUser.tsx, src/libs/hooks/useLogin.tsx, src/libs/hooks/useScroll.tsx, src/libs/hooks/useToken.tsx, src/libs/utils.ts, src/pages/home/_Btn.tsx, src/pages/home/index.tsx, src/pages/main/TotalLoans.tsx, src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/pages/products/financial/index.tsx, src/pages/user/Edit.tsx, vite.config.ts
- api 훅 추가 및 업데이트
- main 페이지 api 데이터 적용
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> feat: useGetProducts, useGetRecommendsProducts, useGetUser

src/DevLinks.tsx, src/env.d.ts, src/libs/axiosClient.ts, src/libs/mockup/getOrders.json, src/libs/mockup/getSearch.json, src/pages/home/index.tsx, src/vite-env.d.ts
서버에 배포된 api 요청 관련 메서드를 모두 정의 및 테스트 완료
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> feat: axios methods complete

src/libs/hooks/useLogin.tsx
- 토큰의 캐시타임을 infinity 로 설정
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> fix) set token cacheTime to Infinity

package-lock.json, package.json, src/DevLinks.tsx, src/api/axios.ts, src/components/CheckToken.tsx, src/components/Search.tsx, src/components/User/DeleteAccountModal.tsx, src/components/WishList/WishListElement.tsx, src/libs/axiosClient.ts, src/libs/hooks/useGetOrders.tsx, src/libs/hooks/useGetUser.tsx, src/libs/hooks/useLogin.tsx, src/libs/hooks/usePatchUser.tsx, src/pages/home/index.tsx, src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/pages/products/financial/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/pages/user/Edit.tsx, src/pages/user/index.tsx, src/store/api/apiSlice.ts, src/store/api/origin_apiSlice.ts
로그인시 store 에 accessToken 이 저장되면,
해당 토큰을 사이드바에서 볼수 있고, 복사도 할수 있습니다.
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> feat) token copy

src/api/axios.ts, src/libs/refresh.ts, src/pages/main/index.tsx, src/pages/user/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Fix: Update user, main page

src/App.tsx, src/api/authApi.ts, src/components/SignIn/SignInField.tsx, src/components/SignUp/SalaryField.tsx, src/components/SignUp/SignUpField.tsx, src/components/User/DeleteAccountModal.tsx, src/components/ui/ConfirmModal.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/pages/user/index.tsx
- pull 받고 해결하려다 이것저것 만져서 push전 commit 기록들이 다 날아간거같습니다...ㅠ
- 새로 기능구현 중이었어서 그것만 제외하고 스타일링은 수정해서 update해놨습니다.
=> Design: Update SignIn, SignUp, User page

src/components/FinancialProdCard.tsx, src/components/Search.tsx, src/components/ui/Navigation/index.tsx, src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/pages/products/financial/index.tsx
- 알릴사항 1
- 알릴사항 2
[검색페이지, 상품상세페이지]
- 피그마 참고해서 css 수정
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> design: Modify Css Styles

src/pages/ProtectedRoute.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Fix: Update protectedRoute.tsx

src/libs/axiosClient.ts, src/pages/home/index.tsx, src/pages/products/financial/[financialId].tsx, src/store/api/apiSlice.ts
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> resolve conflict with hyunseoo

src/libs/utils.ts, src/pages/ProtectedRoute.tsx, src/pages/main/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> feat: error blcok code in utils.ts

src/components/SignIn/SignInField.tsx, src/components/SignUp/SalaryField.tsx, src/components/User/DeleteAccountModal.tsx, src/libs/Cookie.ts, src/pages/ProtectedRoute.tsx, src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/pages/signup/index.tsx, src/pages/user/index.tsx, src/router.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- main페이지에 navigation 컴포넌트 적용
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Design: scroll style

src/components/MyCart/CartElement.tsx, src/components/Nav/index.tsx, src/components/ui/ConfirmModal.tsx, src/pages/main/index.tsx, src/pages/user/MyCart.tsx, src/pages/user/OrderList.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Feat: 장바구니 페이지에서 신청이 되면 신청페이지로 이동하도록 변경

src/App.tsx, src/pages/main/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Design: Update main page

src/components/FinancialProdCard.tsx, src/components/Search.tsx, src/pages/products/financial/index.tsx
- 알릴사항 1
- 알릴사항 2
[financial]
- 검색 화면에서 '내가 가입할 수 있는 상품만 보기' 체크시 바로 검색 요청
보냄
- 검색 응답 데이터 없을 때 '검색 결과가 없습니다' 안내 문구 추가
- 검색 화면에서 예상금리 7.7%로 고정되서 나오던 내용 수정
- 검색 화면에도 메인의 scrollToTop 버튼 추가
- 안쓰는 모달창 삭제
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> fix: Add search checkbox event

src/components/CheckToken.tsx, src/pages/signin/index.tsx, src/pages/user/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Fix: Remove cogoToast

src/components/MyCart/Card.tsx, src/components/MyCart/CartElement.tsx, src/components/OrderList/OrderListCard.tsx, src/components/WishList/WishListElement.tsx, src/components/ui/ConfirmModal.tsx
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Style: 전체 width 변경으로 인해 장바구니, 관심상품, 구매내역 페이지 카드 스타일 수정

src/components/MyCart/CartElement.tsx, src/pages/user/MyCart.tsx
기능 잘 되는지 한번만 확인부탁드려요 ㅠ
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Feat: 장바구니 체크박스로 변경

functions/api/auth/deleteUser.js, functions/api/auth/getUser.js, functions/api/auth/patchUser.js, functions/api/baskets/deleteBaskets.js, functions/api/orders/deleteOrders.js, functions/api/products/getDetails.js, functions/api/wishlists/deleteWishlists.js, functions/api/wishlists/getWishlists.js, functions/index.js
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> test gitignoring

README.md, src/DevLinks.tsx, src/env.d.ts, src/firebase/fb.ts, src/libs/axiosClient.ts, src/pages/main/SlideCard.tsx, src/pages/main/Slider.tsx, src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/store/api/apiSlice.ts, src/store/api/cartApiSlice.ts, src/store/api/orderApiSlice.ts, src/store/api/wishlistApiSlice.ts
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> test: axiosClient.ts methods

src/components/MyCart/CartElement.tsx, src/components/OrderList/OrderListElement.tsx, src/components/WishList/WishListElement.tsx, src/pages/products/financial/[financialId].tsx, src/pages/user/MyCart.tsx, src/pages/user/OrderList.tsx, src/pages/user/WishList.tsx, src/store/api/cartApiSlice.ts, src/store/api/orderApiSlice.ts, src/store/api/wishlistApiSlice.ts
update cart, wishlist, orderlist, financial page code
장바구니 기능, 관심상품 기능, 상품신청 기능 코드 수정했습니다!
작동 안되는 기능 있으면 말씀해주세요
페이지 로딩시 스켈레톤이 이상한데 고치겠습니다
=> Update Page with new APIs

src/App.tsx, src/DevLinks.tsx, src/libs/axiosClient.ts
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> hidden devLinks component

src/pages/main/index.tsx, src/pages/products/financial/[financialId].tsx, src/pages/signin/index.tsx, src/pages/user/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> set the default login account as test@test.com

functions/api/products/getSearch.js, src/components/Search.tsx, src/env.d.ts, src/libs/axiosClient.ts, src/pages/products/financial/index.tsx, src/vite-env.d.ts
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Feat: getSearch api 수정

functions/api/products/getSearch.js, src/libs/axiosClient.ts, src/pages/products/financial/index.tsx
- 알릴사항 1
- 알릴사항 2
[페이지명]
- 작업내용 1
- 작업내용 2
[작업제목]
[작업제목]
- 작업내용
- 작업내용
=> Feat: 전체 검색 api 수정
